"""jolo - Devcontainer + Git Worktree Launcher (internal package)."""

import subprocess  # noqa: F401 - re-exported for test mocking (jolo.subprocess.run)

from _jolo.cli import (  # noqa: F401
    check_tmux_guard,
    clipboard_copy,
    detect_hostname,
    find_git_root,
    generate_random_name,
    get_container_name,
    is_port_available,
    parse_args,
    parse_copy,
    parse_flavor_arg,
    parse_mount,
    random_port,
    read_port_from_devcontainer,
    select_flavors_interactive,
    slugify_prompt,
    verbose_cmd,
    verbose_print,
)
from _jolo.commands import (  # noqa: F401
    ensure_research_repo,
    get_agent_command,
    get_agent_name,
    infer_repo_name,
    load_config,
    main,
    run_attach_mode,
    run_clone_mode,
    run_create_mode,
    run_delete_mode,
    run_doctor_mode,
    run_exec_mode,
    run_init_mode,
    run_list_global_mode,
    run_list_mode,
    run_port_mode,
    run_prune_global_mode,
    run_prune_mode,
    run_research_mode,
    run_spawn_mode,
    run_status_mode,
    run_stop_mode,
    run_tree_mode,
    run_up_mode,
    spawn_tmux_multipane,
)
from _jolo.constants import (  # noqa: F401
    ADJECTIVES,
    DEFAULT_CONFIG,
    FLAVOR_LANGUAGE,
    HAVE_ARGCOMPLETE,
    NOUNS,
    PORT_MAX,
    PORT_MIN,
    PRECOMMIT_HOOKS,
    VALID_FLAVORS,
    VERBOSE,
)
from _jolo.container import (  # noqa: F401
    build_devcontainer_json,
    devcontainer_exec_command,
    devcontainer_exec_tmux,
    devcontainer_up,
    find_containers_for_project,
    find_stopped_containers_for_project,
    get_container_for_workspace,
    get_container_runtime,
    is_container_running,
    list_all_devcontainers,
    reassign_port,
    remove_container,
    set_port,
    stop_container,
)
from _jolo.setup import (  # noqa: F401
    add_user_mounts,
    add_worktree_git_mount,
    clear_directory_contents,
    copy_template_files,
    copy_user_files,
    get_secrets,
    scaffold_devcontainer,
    setup_credential_cache,
    setup_emacs_config,
    setup_notification_hooks,
    setup_stash,
    sync_devcontainer,
    write_prompt_file,
)
from _jolo.templates import (  # noqa: F401
    generate_precommit_config,
    get_coverage_config,
    get_justfile_content,
    get_motd_content,
    get_precommit_install_command,
    get_project_init_commands,
    get_scaffold_files,
    get_test_framework_config,
    get_type_checker_config,
)
from _jolo.worktree import (  # noqa: F401
    branch_exists,
    find_project_workspaces,
    find_stale_worktrees,
    get_or_create_worktree,
    get_worktree_path,
    list_worktrees,
    remove_worktree,
    validate_create_mode,
    validate_init_mode,
    validate_tree_mode,
)
